apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator-deployment
  labels:
    app: simulator
    version: "0.3"
spec:
  replicas: 2000
  selector:
    matchLabels:
      app: simulator
      version: "0.3"
  template:
    metadata:
      labels:
        app: simulator
        version: "0.3"
    spec:
      containers:
      - name: simulator
        image: gcr.io/lxd-project/simulator:0.3
        imagePullPolicy: Always
        env:
        - name: project
          value: lxd-project
        - name: topic
          value: gaming-analytics-topic
        - name: interval
          value: "0.1"
        resources:
          requests:
            cpu: "100m"
            memory: "500Mi"
          limits:
            cpu: "200m"
            memory: "1000Mi"